### ISSUE TITLE
Proof of Concept Signalen frontend

### ISSUE THREAD

**Issue by bartjkdp** [delta10/signalen-frontend#3]
We would like to explore if it is a good idea to choose a different tech stack for developing the Signalen frontend. We would like to explore this in order to:

- Get a better themeable layout, that can easily be modified to the theme of a municipality (with 5 - 10 settings, e.g. typography, logo, favicon / app icon, primary and secondary colour).
- Improve developer productivity.
- Get a faster UI.
- Get a more accessible UI.
- Provide multilingual support (English and Dutch).

The scope for the PoC is now limited to the reporting part of the Signalen frontend. We would like to answer the following question with the Proof of Concept:

"Is it a good idea to choose a different tech stack and accept the work that is involved with rewriting? Or is it a better idea to continue developing within the current codebase and make iterative changes there".

## Themeable layout

Some municipalities that are currently using Signalen:

- [Gemeente Amsterdam](https://meldingen.amsterdam.nl)
- [Gemeente Utrecht](https://meldingen.utrecht.nl)
- [Gemeente Heerlen](https://meldingen.heerlen.nl)
- [Gemeente Leeuwarden](https://meldingen.leeuwarden.nl)
- [Gemeente 's-Hertogenbosch](https://meldingen.s-hertogenbosch.nl)

## Improve developer productivity

The setup with create-react-app, Redux and the Amsterdam Styled Components library makes things sometimes hard to change.

## Faster UI

We currently ship one large bundle (that includes reporter and management UI) to the user. The application is entirely client-side rendered. This makes loading times - especially on mobile devices - long. The Lighthouse score on performance is only 37:

![image](https://github.com/delta10/signalen-frontend/assets/5213690/4fb222c5-b86b-4402-b443-b89dc39e1a38)

## Accessible UI

The current UI is periodically tested on WCAG and a lot of improvements already have been done, but new functionality often generates new accessibility problems. Would switching to a component library that had WCAG built-in help us here?

## Multilingual support

Currently the Dutch language is hardcoded everywhere in the application. We would like to support at least English, but in the future also other languages as well as we scale up the project to other European cities.

**Comment by justiandevs** [comment]
At the moment, I've built the Proof of Concept (PoC), which can be accessed via: https://signalen-frontend-poc.vercel.app/en/incident.

### Throughout the development process, I made several tech stack choices that led to a few key observations:

- I opted to work with Next.js v14 and utilized the app directory within the PoC. This choice allowed for optimizations regarding caching and data fetching, leveraging server actions, and server components, which, when used cleverly, can greatly enhance performance.
- Radix UI for components: I chose a UI library providing headless UI components with accessibility in mind by default. Coupled with Tailwind CSS, this library offers extensive possibilities to create nearly any component.
- Tailwind CSS for styling: It provides ample potential for inline styling using utility classes within and outside components.
React Hook Form for form validation alongside Zod for client-side validation.
- Class Variance Authority for components with diverse variants, enabling the creation of different versions and accessing the appropriate variant for each component via props.
- Next-intl for translations: It's an i18n library compatible with Server and Client Side Components, making it an ideal solution for applications built with Next 13 and above.
- React-map-gl: This map library works with Mapbox or Mapbox forks. I chose to work with react-map-gl due to its seamless integration with maptiler, which aligned with my vision for map functionality.
- Typescript-openapi-generator: This generator facilitates the creation of clients based on structured YAML API configurations. It simplifies API communication and provides built-in type support for response, request, and error objects, enhancing the developer experience.

### Key conclusions drawn from this process include:

- A significant improvement in developer experience by leveraging this or a similar tech stack. Building with well-established open-source libraries/frameworks allows rapid development due to abundant resources available for implementing various functionalities. Utilizing Radix UI components alleviates concerns about making components accessible, a typically challenging and time-consuming task.
- The chosen setup facilitates multilingual capabilities efficiently. By configuring the configuration.json file and providing translation files for each chosen locale, the application can swiftly support multiple languages for end-users. The use of next-i18n ensures multilingual functionality across Server Components and Client Components.
- Enhanced UI speed: Achieving a Lighthouse score of 90%+ signifies significant progress. This improvement stems from not needing to fetch the entire application bundle but rather fetching the bundle determined by Next.js, based on how the application is structured (always consider at least the React bundle + the current page you're on).
- Themeable layout: By extending the Tailwind config and utilizing a configuration.json file, modifying the theme of the Signalen PoC is straightforward. The configurable properties in configuration.json are thoughtfully crafted based on the NL Design System Figma from Gemeente Utrecht.
